### ISSUE TITLE
ArrayConverter cannot convert from System.String

### ISSUE THREAD

**Issue by Leuconoe** [sinbad/UnityCsvUtil#7]
How should I use an int array?

I have tested it in several ways, but it doesn't work.
Even in the C# documentation, I can't fix the problem as there are no samples.
can you help me?

thank uou
![주석 2020-09-10 182812](https://user-images.githubusercontent.com/6531761/92711646-ac056c00-f393-11ea-8b3e-6b1ad6f561d4.png)
![주석 2020-09-10 183152](https://user-images.githubusercontent.com/6531761/92711926-ed961700-f393-11ea-9f84-d89c8d7eb07f.png)
![주석 2020-09-10 182952](https://user-images.githubusercontent.com/6531761/92711655-ad369900-f393-11ea-9bce-b05db34e1768.png)

**Comment by sinbad** [comment]
This is not supported yet because .Net's ArrayConverter can't operate on strings. Embedding 1:n relationships in the rows was not something I ever needed. 

I'm not working on this project any more (I don't use Unity any more) but you could modify ParseString to special case for array types if you wanted; use Split() on the incoming string and populate an array by parsing each element separately.

**Comment by Leuconoe** [comment]
thank you!
